# Generated by Django 2.0.2 on 2018-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nick_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
