# Generated by Django 2.0.2 on 2018-03-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time when current record is created')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time when current record is modified')),
                ('login_ip', models.GenericIPAddressField()),
                ('member', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
