# Generated by Django 2.0.2 on 2018-03-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Mid'), (1, 'Male'), (2, 'Female')]),
        ),
    ]
