# Generated by Django 2.0.2 on 2018-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_password'),
    ]

    operations = [
        migrations.RemoveField(model_name='member',
            name='gender'),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
