# Generated by Django 2.0.2 on 2018-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180303_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
